# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: aiopriman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - 3.7 
          - 3.8 
          - 3.9

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install

    - name: Lint with flake8
      run: |
        poetry run flake8 aiopriman examples tests
  
    - name: Mypy check
      run: |
        poetry run mypy aiopriman --strict

    - name: Test with pytest
      run: |
          poetry run pytest --cov=aiopriman --cov-config .coveragerc --cov-report=xml

    - name: Check code-style (Black)
      run: |
          poetry run black --check --diff aiopriman examples tests

    - uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
        flags: unittests
        name: py-${{ matrix.python-version }}-${{ matrix.os }}
